In [8]:
import numpy
arr=numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [9]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [13]:
import numpy as np
print(np. __version__)

1.21.5


In [14]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(type(arr))

<class 'numpy.ndarray'>


In [15]:
#zero dimension
import numpy as np
arr=np.array(42)
print(arr)

42


In [16]:
#one dimension
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [17]:
#two dimension
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [18]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr.ndim)

2
